all: extract-ec

extract-ec: ../../jasmin/compiler/jasminc ../Jasmin/passCertGenerator.jazz
		../../jasmin/compiler/jasminc ../Jasmin/passCertGenerator.jazz -ec generate_password -oec passCertGenerator_jazz.ec

