all: extract-ec

extract-ec: ../../jasmin/compiler/jasminc ../Jasmin/passCertGenerator.jazz
		../../jasmin/compiler/jasminc ../Jasmin/passCertGenerator.jazz -ec generatePassword -oec passCertGenerator_jazz.ec

